### ISSUE TITLE
Trademark breach

### ISSUE THREAD

**Issue by CallOfMinecraft** [greeves12/COD#2]
Hello, I'm just gonna leave this here, I was made aware that the name CallOfMinecraft or a subsidiary, in this case the abbreviated variant "COM" is being used illegally, please cease, the only one with permission from myself, The Legal holder of COM: Warfare and all of its subsidiaries is Mr_Rhetorical, you do not have my permission, please rebrand, change the name here too: https://www.spigotmc.org/resources/com-warfare.51211/updates
I'm just asking politely so it doesn't need to escalate, it's up to you what happens next, but hopefully you understand that I'm okay with the distribution of your project, just protecting my brand by requesting you remove it from your product.

**Comment by greeves12** [comment]
No and no. You decided to take my code from my contributions of cod warfare and sell it, so if you try and DMCA me, I will do the exact same thing, except it will be 10x worse for you. I know it's you Mr_Rhetorical, I thought you would atleast have the balls to come talk to me without creating another account. Don't think for a second I dont know you're the one who cloned this repository, hopefully you're not planning on selling my code again.

**Comment by CallOfMinecraft** [comment]
false allegations will get you nowhere with me, I am not a person selling code, I simply own the product name affiliated with it. this issue was not resolve, but will be, good day sir/madam.

**Comment by greeves12** [comment]
You can't even proofread your comments, so how could you try and file a DMCA to the government?
